install: carthage update --cache-builds --platform iOS
language: swift
os: osx
osx_image: xcode10.2
script:
  xcodebuild -scheme Medi8 -project Medi8.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' test
after_success:
  bash <(curl -s https://codecov.io/bash)

